kind: Deployment
apiVersion: apps/v1
metadata:
  name: whoami
  labels:
    app: whoami
    task: http

spec:
  replicas: 1
  selector:
    matchLabels:
      app: whoami
      task: http
  template:
    metadata:
      labels:
        app: whoami
        task: http
    spec:
      containers:
        - name: whoami
          image: traefik/whoami
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: whoami
spec:
  ports:
    - name: http
      port: 80
  selector:
    app: whoami
    task: http

---
apiVersion: traefik.containo.us/v1alpha1
kind: TLSOption
metadata:
  name: whoami-mtls
spec:
  minVersion: VersionTLS12
  maxVersion: VersionTLS13
  clientAuth:
    secretNames:
      - mtls-ca
    clientAuthType: RequireAndVerifyClientCert
  sniStrict: true
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: myingressroute
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`whoami.docker.localhost`)
    kind: Rule
    services:
    - name: whoami
      port: 80
  tls:
    # Traefik served TLS certificate
    secretName: whoami-cert
    # mTLS between client and Traefik
    options:
      name: whoami-mtls
